version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: payroll
      POSTGRES_PASSWORD: payroll
      POSTGRES_DB: payroll
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  db_data:
